[package]
name = "learn_rust"
version = "0.1.0"
authors = ["vicsn <vicsn@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libmath = "0.2.1"
itertools = "0.8.0"
peroxide = "0.16.5"
